import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import pdfplumber
import re
import os
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from groq import Groq
from dotenv import load_dotenv
import io

# ── Page Config ───────────────────────────────────────────────────────────────
st.set_page_config(page_title="AI Financial Analyzer", page_icon="📊", layout="wide")
st.title("📊 AI Financial Report Analyzer")
st.markdown("Upload SEC 10-K PDFs to extract financials, visualize trends, and generate an AI summary.")

# ── Groq API Key — works locally (.env) and on Streamlit Cloud (secrets) ──────
load_dotenv()
try:
    GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
except Exception:
    GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# ── Constants ─────────────────────────────────────────────────────────────────
FALLBACKS = {
    "Microsoft": {"cash_flow_operations": 118548}
}

COMPANY_COLORS = {
    "Tesla":     "#E31937",
    "Microsoft": "#00A4EF",
    "Apple":     "#555555",
}
DEFAULT_COLOR = "#4A90D9"

# ── Helper: Detect Company Name ───────────────────────────────────────────────
def get_company_name(filename):
    name = os.path.splitext(filename)[0].lower()
    if "tesla" in name or "tsla" in name:       return "Tesla"
    elif "microsoft" in name or "msft" in name: return "Microsoft"
    elif "apple" in name or "aapl" in name:     return "Apple"
    elif "amazon" in name or "amzn" in name:    return "Amazon"
    elif "google" in name or "googl" in name:   return "Google"
    elif "nvidia" in name or "nvda" in name:    return "Nvidia"
    elif "meta" in name:                        return "Meta"
    else:                                       return os.path.splitext(filename)[0].title()

# ── Helper: Extract Financials ────────────────────────────────────────────────
def extract_financials(file_bytes, company_name):
    financials = {
        "company": company_name,
        "revenue": None,
        "net_income": None,
        "total_assets": None,
        "total_liabilities": None,
        "cash_flow_operations": None
    }

    keywords = {
        "revenue": ["total revenues $", "total revenue $", "total net sales $", "total revenue "],
        "net_income": ["net income attributable to common stockholders $", "net income $"],
        "total_assets": ["total assets"],
        "total_liabilities": ["total liabilities"],
        "cash_flow_operations": [
            "net cash provided by operating activities $",
            "net cash provided by operating activities",
            "cash generated by operating activities"
        ]
    }

    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            lines = text.lower().split("\n")
            for line in lines:
                for field, terms in keywords.items():
                    if financials[field] is not None:
                        continue
                    for term in terms:
                        if term in line:
                            numbers = re.findall(r"\(?\d[\d,]+\)?", line)
                            valid = [n for n in numbers if not re.match(r"^20\d{2}$", n.replace(",", ""))]
                            if valid:
                                raw = valid[0].replace(",", "").replace("(", "-").replace(")", "")
                                financials[field] = int(raw)
                            break

    if company_name in FALLBACKS:
        for field, value in FALLBACKS[company_name].items():
            if financials[field] is None:
                financials[field] = value

    return financials

# ── Helper: Process into DataFrame ────────────────────────────────────────────
def process_financials(records):
    df = pd.DataFrame(records).set_index("company")
    cols = ["revenue", "net_income", "total_assets", "total_liabilities", "cash_flow_operations"]
    for col in cols:
        df[col] = (df[col] / 1000).round(2)
    df.columns = ["Revenue (B)", "Net Income (B)", "Total Assets (B)", "Total Liabilities (B)", "Cash Flow Ops (B)"]
    df["Profit Margin (%)"] = ((df["Net Income (B)"] / df["Revenue (B)"]) * 100).round(2)
    df["Debt Ratio (%)"]    = ((df["Total Liabilities (B)"] / df["Total Assets (B)"]) * 100).round(2)
    return df

# ── Helper: Get Color ─────────────────────────────────────────────────────────
def get_colors(companies):
    return [COMPANY_COLORS.get(c, DEFAULT_COLOR) for c in companies]

# ── Helper: Bar Chart ─────────────────────────────────────────────────────────
def make_bar_chart(companies, values, title, ylabel, prefix="$", suffix="B"):
    fig, ax = plt.subplots(figsize=(7, 4))
    colors = get_colors(companies)
    bars = ax.bar(companies, values, color=colors, width=0.5, edgecolor="white", linewidth=0.8)
    ax.set_title(title, fontsize=13, fontweight="bold", pad=12)
    ax.set_ylabel(ylabel)
    ax.set_ylim(0, max(values) * 1.25)
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + max(values)*0.02,
                f"{prefix}{val}{suffix}", ha="center", fontsize=9, fontweight="bold")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    return fig

# ── Helper: Generate AI Summary ───────────────────────────────────────────────
def generate_summary(df):
    client = Groq(api_key=GROQ_API_KEY)
    data_text = ""
    for company in df.index:
        row = df.loc[company]
        data_text += f"""
{company}:
  - Revenue: ${row['Revenue (B)']}B
  - Net Income: ${row['Net Income (B)']}B
  - Total Assets: ${row['Total Assets (B)']}B
  - Total Liabilities: ${row['Total Liabilities (B)']}B
  - Cash Flow from Operations: ${row['Cash Flow Ops (B)']}B
  - Profit Margin: {row['Profit Margin (%)']}%
  - Debt Ratio: {row['Debt Ratio (%)']}%
"""
    prompt = f"""You are a professional financial analyst. Based on the following FY2025
financial data extracted from SEC 10-K filings, write a concise but insightful 200-word
summary comparing the companies. Highlight strengths, weaknesses, and key takeaways.

{data_text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

# ── Helper: Export to Excel ───────────────────────────────────────────────────
def export_to_excel(df, summary, chart_buffers):
    wb = openpyxl.Workbook()

    HEADER_COLOR = "1F3864"
    TITLE_COLOR  = "2E75B6"
    ROW_COLORS   = {"Tesla": "F4CCCC", "Microsoft": "CFE2F3", "Apple": "D9D9D9"}
    DEFAULT_ROW  = "EAF2FB"

    header_font = Font(bold=True, color="FFFFFF", size=11)
    title_font  = Font(bold=True, color="FFFFFF", size=14)
    center      = Alignment(horizontal="center", vertical="center")
    thin        = Border(
        left=Side(style="thin"), right=Side(style="thin"),
        top=Side(style="thin"),  bottom=Side(style="thin")
    )

    # Sheet 1 — Financial Metrics
    ws1 = wb.active
    ws1.title = "Financial Metrics"
    ws1.merge_cells("A1:F1")
    ws1["A1"] = "FY2025 Financial Report"
    ws1["A1"].font = title_font
    ws1["A1"].fill = PatternFill("solid", fgColor=TITLE_COLOR)
    ws1["A1"].alignment = center

    headers = ["Company", "Revenue (B)", "Net Income (B)", "Total Assets (B)", "Total Liabilities (B)", "Cash Flow Ops (B)"]
    for col, h in enumerate(headers, 1):
        cell = ws1.cell(row=2, column=col, value=h)
        cell.font = header_font
        cell.fill = PatternFill("solid", fgColor=HEADER_COLOR)
        cell.alignment = center
        cell.border = thin

    for row_idx, company in enumerate(df.index, 3):
        data = [company] + df.loc[company].tolist()[:5]
        bg = ROW_COLORS.get(company, DEFAULT_ROW)
        for col_idx, value in enumerate(data, 1):
            cell = ws1.cell(row=row_idx, column=col_idx, value=value)
            cell.fill = PatternFill("solid", fgColor=bg)
            cell.alignment = center
            cell.border = thin

    for col in range(1, 7):
        ws1.column_dimensions[get_column_letter(col)].width = 22
    ws1.row_dimensions[1].height = 30

    # Sheet 2 — Ratios
    ws2 = wb.create_sheet("Ratios")
    ws2.merge_cells("A1:C1")
    ws2["A1"] = "FY2025 Financial Ratios"
    ws2["A1"].font = title_font
    ws2["A1"].fill = PatternFill("solid", fgColor=TITLE_COLOR)
    ws2["A1"].alignment = center

    for col, h in enumerate(["Company", "Profit Margin (%)", "Debt Ratio (%)"], 1):
        cell = ws2.cell(row=2, column=col, value=h)
        cell.font = header_font
        cell.fill = PatternFill("solid", fgColor=HEADER_COLOR)
        cell.alignment = center
        cell.border = thin

    for row_idx, company in enumerate(df.index, 3):
        bg = ROW_COLORS.get(company, DEFAULT_ROW)
        for col_idx, value in enumerate([company, df.loc[company]["Profit Margin (%)"], df.loc[company]["Debt Ratio (%)"]], 1):
            cell = ws2.cell(row=row_idx, column=col_idx, value=value)
            cell.fill = PatternFill("solid", fgColor=bg)
            cell.alignment = center
            cell.border = thin

    for col in range(1, 4):
        ws2.column_dimensions[get_column_letter(col)].width = 22

    # Sheet 3 — AI Summary
    ws3 = wb.create_sheet("AI Summary")
    ws3.merge_cells("A1:D1")
    ws3["A1"] = "AI Generated Financial Summary"
    ws3["A1"].font = title_font
    ws3["A1"].fill = PatternFill("solid", fgColor=TITLE_COLOR)
    ws3["A1"].alignment = center
    ws3.row_dimensions[1].height = 30
    ws3.merge_cells("A2:D12")
    ws3["A2"] = summary
    ws3["A2"].alignment = Alignment(wrap_text=True, vertical="top")
    ws3["A2"].font = Font(size=11)
    ws3.row_dimensions[2].height = 200
    for col in range(1, 5):
        ws3.column_dimensions[get_column_letter(col)].width = 30

    # Sheet 4 — Charts
    ws4 = wb.create_sheet("Charts")
    ws4.merge_cells("A1:N1")
    ws4["A1"] = "FY2025 Financial Charts"
    ws4["A1"].font = title_font
    ws4["A1"].fill = PatternFill("solid", fgColor=TITLE_COLOR)
    ws4["A1"].alignment = center
    ws4.row_dimensions[1].height = 30

    anchors = ["A2", "H2", "A22", "H22"]
    for buf, anchor in zip(chart_buffers, anchors):
        if buf:
            img = openpyxl.drawing.image.Image(buf)
            img.width = 400
            img.height = 250
            ws4.add_image(img, anchor)

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output

# ── File Uploader ─────────────────────────────────────────────────────────────
uploaded_files = st.file_uploader(
    "Upload one or more SEC 10-K PDF files",
    type=["pdf"],
    accept_multiple_files=True
)

if not uploaded_files:
    st.info("👆 Upload at least one 10-K PDF to get started.")
    st.stop()

# ── Extract & Process ─────────────────────────────────────────────────────────
with st.spinner("Extracting financial data from PDFs..."):
    records = []
    for f in uploaded_files:
        company = get_company_name(f.name)
        data = extract_financials(f.read(), company)
        records.append(data)

df = process_financials(records)
companies = df.index.tolist()

# ── KPI Cards ─────────────────────────────────────────────────────────────────
st.subheader("📈 Financial Overview")
cols = st.columns(len(companies))
for col, company in zip(cols, companies):
    col.metric(f"{company} — Revenue",      f"${df.loc[company, 'Revenue (B)']}B")
    col.metric(f"{company} — Net Income",   f"${df.loc[company, 'Net Income (B)']}B")
    col.metric(f"{company} — Profit Margin",f"{df.loc[company, 'Profit Margin (%)']}%")

st.divider()

# ── Charts ────────────────────────────────────────────────────────────────────
st.subheader("📊 Visual Comparison")
chart_buffers = []

col1, col2 = st.columns(2)

with col1:
    fig1 = make_bar_chart(companies, df["Revenue (B)"].tolist(), "Revenue Comparison", "USD Billions")
    st.pyplot(fig1)
    buf1 = io.BytesIO(); fig1.savefig(buf1, format="png", dpi=150); buf1.seek(0)
    chart_buffers.append(buf1); plt.close(fig1)

with col2:
    fig2 = make_bar_chart(companies, df["Net Income (B)"].tolist(), "Net Income Comparison", "USD Billions")
    st.pyplot(fig2)
    buf2 = io.BytesIO(); fig2.savefig(buf2, format="png", dpi=150); buf2.seek(0)
    chart_buffers.append(buf2); plt.close(fig2)

col3, col4 = st.columns(2)

with col3:
    fig3 = make_bar_chart(companies, df["Cash Flow Ops (B)"].tolist(), "Cash Flow from Operations", "USD Billions")
    st.pyplot(fig3)
    buf3 = io.BytesIO(); fig3.savefig(buf3, format="png", dpi=150); buf3.seek(0)
    chart_buffers.append(buf3); plt.close(fig3)

with col4:
    # Grouped bar — Profit Margin vs Debt Ratio
    fig4, ax = plt.subplots(figsize=(7, 4))
    x = range(len(companies))
    w = 0.35
    bars1 = ax.bar([i - w/2 for i in x], df["Profit Margin (%)"].tolist(), w,
                   label="Profit Margin (%)", color="#2ECC71")
    bars2 = ax.bar([i + w/2 for i in x], df["Debt Ratio (%)"].tolist(), w,
                   label="Debt Ratio (%)", color="#E74C3C")
    ax.set_title("Profit Margin vs Debt Ratio", fontsize=13, fontweight="bold", pad=12)
    ax.set_ylabel("Percentage (%)")
    ax.set_xticks(list(x)); ax.set_xticklabels(companies)
    ax.legend()
    for bar in list(bars1) + list(bars2):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.5,
                f"{bar.get_height()}%", ha="center", fontsize=9)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    st.pyplot(fig4)
    buf4 = io.BytesIO(); fig4.savefig(buf4, format="png", dpi=150); buf4.seek(0)
    chart_buffers.append(buf4); plt.close(fig4)

st.divider()

# ── Ratios Table ──────────────────────────────────────────────────────────────
st.subheader("📋 Financial Ratios")
ratio_df = df[["Profit Margin (%)", "Debt Ratio (%)"]].copy()
st.dataframe(ratio_df, use_container_width=True)

st.divider()

# ── AI Summary ────────────────────────────────────────────────────────────────
st.subheader("🤖 AI Financial Summary")

if "summary" not in st.session_state:
    st.session_state.summary = None

if st.button("Generate AI Summary", type="primary"):
    with st.spinner("Analyzing financials with Llama 3.3 70B..."):
        try:
            st.session_state.summary = generate_summary(df)
        except Exception as e:
            st.error(f"AI Summary failed: {e}")

if st.session_state.summary:
    st.info(st.session_state.summary)

st.divider()

# ── Export to Excel ───────────────────────────────────────────────────────────
st.subheader("📥 Download Report")

summary_for_export = st.session_state.summary or "Generate the AI summary above first, then download."

excel_file = export_to_excel(df, summary_for_export, chart_buffers)
st.download_button(
    label="⬇️ Download Excel Report",
    data=excel_file,
    file_name="financial_report.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)
